// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kksozunhdekaxywiognx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtrc296dW5oZGVrYXh5d2lvZ254Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzOTE5ODYsImV4cCI6MjA2Mzk2Nzk4Nn0.KUVm-10SxyqddwkyKg3GCcwg5hKNnXxVtPGF2p_2a3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);